version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: laravel-app
    volumes:
      - ./app:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db
      - redis
    working_dir: /var/www/html
    command: bash -c "composer install && php artisan key:generate && php-fpm"

  web:
    image: nginx:latest
    container_name: laravel-web
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app:/var/www/html
    ports:
      - "8080:80"
    networks:
      - laravel-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: laravel-redis
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - laravel-network

volumes:
  db_data:

networks:
  laravel-network:
    driver: bridge

